version: '3'

networks:
  node-network:

services:
  test-app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - postgres
    networks:
      - node-network

  mongodb:
    image: mongo:latest
    restart: always
    networks:
      - node-network
    ports:
      - "27017:27017"

  postgres:
    image: postgres:latest
    restart: always
    networks:
      - node-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
